// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.apache.commons.io.FileUtils;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.openqa.selenium.*;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.File;

public class CarTaxTest {
  private static WebDriver driver;


  @BeforeAll
  static void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();


  }
  @AfterAll
  static void tearDown() {
    driver.quit();
  }

  @Test
  public void carTax() throws Exception {
    driver.get("https://www.gov.uk/");
    driver.manage().window().setSize(new Dimension(1200, 900));
    driver.findElement(By.xpath("//*[starts-with(@id, 'search-main-')]")).click();
    driver.findElement(By.xpath("//*[starts-with(@id, 'search-main-')]")).sendKeys("car tax");
    driver.findElement(By.cssSelector(".govuk-\\!-margin-top-5 .gem-c-search__submit")).click();
    driver.findElement(By.linkText("Tax your vehicle")).click();

    // Take a screenshot of what's currently on the page,
    // and store it in a file 'makers.png' in your project root
    takeScreenshot(driver, "cartax.png");


  }


  public static void takeScreenshot(WebDriver webdriver,String desiredPath) throws Exception{
    TakesScreenshot screenshot = ((TakesScreenshot)webdriver);
    File screenshotFile = screenshot.getScreenshotAs(OutputType.FILE);
    File targetFile = new File(desiredPath);
    FileUtils.copyFile(screenshotFile, targetFile);
  }
}
