// Generated by Selenium IDE

import org.junit.jupiter.api.*;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.firefox.FirefoxDriver;

import java.util.HashMap;
import java.util.Map;

import static org.junit.Assert.*;
public class ZaraPerfumeTest {
  private static WebDriver driver;

  @BeforeAll
  static void setUp() {
    driver = new FirefoxDriver();
  }

  @Test
  public void zaraPerfume() {
    driver.get("https://www.zara.com/uk/");
    driver.manage().window().setSize(new Dimension(1040, 930));
    driver.findElement(By.id("onetrust-accept-btn-handler")).click();
    driver.findElement(By.cssSelector("a[data-qa-id='header-search-bar-link']")).click();
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys("perfume new york");
    driver.findElement(By.id("search-products-form-combo-input")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".media-image__image")).click();
  }

  @AfterAll
  static void tearDown() {
    driver.quit();
  }

}
